import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Header from '@/components/Header'
import Footer from '@/components/Footer'; 

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className={`${nunito.className} bg-gradient-to-r from-pink-500 via-red-500 to-yellow-500 bg-[length:600%_600%] animate-gradient-animation`}>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
